spring:
  application:
    name: football-service

football:
  third-party:
    base-url: "https://api.football-data.org/v4"
    auth-token: ${FOOTBALL-DATA-TOKEN}

logging:
  level:
    root: INFO
    com.rauloliva.footballservice: DEBUG