<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.rauloliva</groupId>
        <artifactId>football-microservice</artifactId>
        <version>0.0.1-SNAPSHOT-1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>football-api</artifactId>
    <name>football-api</name>
    <description>football-apis</description>

    <properties>
        <java.version>25</java.version>
        <openapi-generator-maven-plugin.version>7.8.0</openapi-generator-maven-plugin.version>

        <!-- dependencies versions -->
        <jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
        <swagger-annotations.version>2.2.15</swagger-annotations.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>${jackson-databind-nullable.version}</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/football-api-openapi-spec.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.rauloliva.football.api</apiPackage>
                            <modelPackage>com.rauloliva.football.dto</modelPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
